trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  GOVERSION: '1.13'

jobs:
  - job: go_lint
    dependsOn: environment
    condition: succeeded()
    steps:
      - script: sudo make lint
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        displayName: 'Run go lint'

  - job: integration_tests
    dependsOn: environment
    condition: succeeded()
    steps:
      - script: make integration
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        displayName: 'Run integration tests'

  - job: unit_tests
    dependsOn: environment
    condition: succeeded()
    steps:
      - script: make test
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        displayName: 'Run unit tests'
      - script: bash <(curl -s https://codecov.io/bash) -f coverage.txt
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        displayName: 'Upload coverage to codecov.io'

  - job: build
    dependsOn: environment
    condition: succeeded()
    steps:
      - script: make go-build
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        displayName: 'Build'