version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  pre_build:
    commands:
      # Make sure we're in the project directory within our GOPATH
      #- cd "/go/src/${PACKAGE}"
      # Fetch all dependencies
      - echo Install dependency
      - make install
  build:
    commands:
      - echo Building the Go code...
      - cd $CODEBUILD_SRC_DIR
      - go build -o bin/api cmd/api

artifacts:
  files:
    - Procfile
    - config.yml
    - bin/api