version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
      nodejs: 10
  build:
    commands:
      - echo Building the Go code...
      - cd $CODEBUILD_SRC_DIR
      - go build -o bin/watchmarket cmd/api