version: '3.7'
services:
  api:
    container_name: api
    build:
      context: .
      args:
        - SERVICE=api
    environment:
      - STORAGE_POSTGRES_URI=postgresql://user:pass@postgres/watchmarket?sslmode=disable
      - STORAGE_REDIS=redis://redis:6379
    ports:
      - 8421:8421
    links:
      - redis
      - postgres
    restart: on-failure

  worker:
    container_name: worker
    build:
      context: .
      args:
        - SERVICE=worker
    environment:
      - STORAGE_POSTGRES_URI=postgresql://user:pass@postgres/watchmarket?sslmode=disable
      - STORAGE_REDIS=redis://redis:6379
    links:
      - postgres
    restart: on-failure

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=watchmarket
    ports:
      - 5432:5432
    restart: on-failure