version: '3.7'
services:
  market_api:
    container_name: market_api
    build:
      context: .
      args:
        - SERVICE=market_api
    ports:
      - 8421:8421
    links:
      - redis

  market_observer:
    container_name: market_observer
    build:
      context: .
      args:
        - SERVICE=market_observer
    links:
      - redis

  swagger_api:
    container_name: swagger_api
    build:
      context: .
      args:
        - SERVICE=swagger_api
    ports:
      - 8423:8423

  redis:
    container_name: redis
    image: neojt/mredis
    ports:
      - 6379:6379
