apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-swagger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "watchmarket.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      name: swagger
  selector:
      name: nginx-proxy