# scaling
apiReplicaCount: 3
workerReplicaCount: 1

image:
  repository: repositoryToReplace
  tag: tagToReplace

posgtres:
  enabled: false
redis:
  enabled: false
config:
  enabled: false
secret:
  enabled: false

apiResources: 
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi
workerResources: 
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi