apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tickers
  namespace: {{ .Release.Namespace }}
  labels:
    app: api-tickers
    chart: {{ template "watchmarket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.apiTickersReplicaCount }}
  selector:
    matchLabels:
      name: api-tickers
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        name: api-tickers
    spec:
      containers:
      - env:
        - name: ELASTIC_APM_SERVICE_NAME
          value: watchmarket-api-tickers
        - name: REST_API_APIS
          value: base,tickers
        envFrom:
        - secretRef:
            name: secrets
            optional: false
        - configMapRef:
            name: configs
            optional: false
        image: "{{ .Values.image.repository }}:api-{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: api-tickers
        ports:
        - containerPort: 8421
          name: 8421tcp01
          protocol: TCP
        resources:
            {{- toYaml .Values.apiTickersResources | nindent 12 }}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-tickers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "watchmarket.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8421
      protocol: TCP
      name: http
  selector:
      name: api-tickers