apiVersion: v1
kind: Service
metadata:
  name: api-info
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "watchmarket.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8421
      protocol: TCP
      name: http
  selector:
      name: api-info
