apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{ .Release.Namespace }}
data:
  {{- range $k, $v := .Values.config }}
  {{- range $kk, $vv := $v }}
    {{ $kk }}: {{ $vv | quote }}
  {{- end }}
  {{- end }}