apiVersion: v1
kind: Secret
metadata:
  name: elastic
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "watchmarket.name" . }}
    chart: {{ template "watchmarket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  admin-user: {{ randAlphaNum 40 | b64enc | quote }}
  admin-password: {{ randAlphaNum 40 | b64enc | quote }}