apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx-proxy
    chart: {{ template "watchmarket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        name: nginx-proxy
    spec:
      containers:
      - env:
        - name: API_CHARTS_URI
          value: http://api-charts:8421
        - name: API_INFO_URI
          value: http://api-info:8421
        - name: API_TICKERS_URI
          value: http://api-tickers:8421
        - name: API_SWAGGER_URI
          value: http://api-swagger:8421
        - name: API_RATES_URI
          value: http://api-rates:8421
        image: "{{ .Values.image.repository }}:{{ .Values.image.nginxProxyTag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: nginx-proxy
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "watchmarket.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
      name: nginx-proxy