apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "watchmarket.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
      name: nginx-proxy