apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx-proxy
    chart: {{ template "watchmarket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: nginx-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        name: nginx-proxy
    spec:
      containers:
      - env:
        - name: API_CHARTS_URI
          value: http://api-charts:8421
        - name: API_INFO_URI
          value: http://api-info:8421
        - name: API_TICKERS_URI
          value: http://api-tickers:8421
        - name: API_SWAGGER_URI
          value: http://api-swagger:8421
        - name: API_RATES_URI
          value: http://api-rates:8421
        image: "{{ .Values.image.repository }}:{{ .Values.image.nginxProxyTag }}"
        imagePullPolicy: IfNotPresent
        name: nginx-proxy
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
