{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "watchmarket.name" . }}
    chart: {{ template "watchmarket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $k, $v := .Values.secrets }}
  {{- range $kk, $vv := $v }}
    {{ $kk }}: {{ $vv | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}