apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "watchmarket.name" . }}
    chart: {{ template "watchmarket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  #- STORAGE_POSTGRES_URI: {{ "postgresql://user:pass@postgres/my_db?sslmode=disable" | b64enc }}
  #- STORAGE_REDIS: {{ "redis://redis:6379" | b64enc }}
  {{- range $k, $v := .Values.secrets }}
  {{- range $kk, $vv := $v }}
    {{ $kk }}: {{ $vv | b64enc }}
  {{- end }}
  {{- end }}