{{- if .Values.seed.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: seed-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: seed-job
    chart: {{ template "watchmarket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations: {}
spec:
  template:
    metadata:
      name: seed-job
      labels:
        name: seed-job
    spec:
      containers:
      - name: seed-job
        envFrom:
        - secretRef:
            name: secrets
            optional: false
        image: "{{ .Values.image.repository }}:{{ .Values.image.seedTag }}"
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 20
{{- end }}