config:
- TEST_API_PORT: 8421
- TEST_API_TICKERS_CACHE_CONTROL: 1m
- TEST_API_TICKERS_RESPECTABLE_VOLUME: 0
- TEST_API_TICKERS_RESPECTABLE_MARKET_CAP: 0
- TEST_API_TICKERS_RESPECTABLE_UPDATE_TIME: 72h
- TEST_API_MODE: release
- TEST_API_APIS: base, tickers, charts, info, swagger, rates
