config:
- REST_API_TICKERS_RESPECTABLE_UPDATE_TIME: 72h
- MARKETS_PRIORITY_TICKERS: coinmarketcap, coingecko, binancedex
- REST_API_UPDATE_TIME_MEMORY_CACHE_RATES: 30s
- STORAGE_POSTGRES_ENV: prod
- WORKER_TICKERS: 1m
- WORKER_RATES: 5m
- MARKETS_COINMARKETCAP_CURRENCY: USD
- REST_API_PORT: 8421
- MARKETS_COINMARKETCAP_WIDGET_API: https://widgets.coinmarketcap.com
- MARKETS_ASSETS: https://raw.githubusercontent.com/trustwallet/assets/master/blockchains
- MARKETS_FIXER_API: https://data.fixer.io/api
- STORAGE_REDIS: redis://localhost:6379
- REST_API_INFO_CACHE_CONTROL: 10m
- REST_API_USE_MEMORY_CACHE: true
- REST_API_CACHE: 15m
- REST_API_REQUEST_LIMIT: 500
- MARKETS_COINMARKETCAP_WEB_API: https://web-api.coinmarketcap.com
- MARKETS_FIXER_CURRENCY: USD
- MARKETS_PRIORITY_CHARTS: coinmarketcap, coingecko
- MARKETS_COINMARKETCAP_KEY: null
- STORAGE_POSTGRES_LOGS: false
- STORAGE_POSTGRES_URI: postgresql://user:pass@localhost/my_db?sslmode=disable
- MARKETS_COINMARKETCAP_API: https://pro-api.coinmarketcap.com
- MARKETS_PRIORITY_RATES: fixer, coinmarketcap, coingecko
- MARKETS_COINGECKO_CURRENCY: USD
- REST_API_APIS: base, tickers, charts, info, swagger, rates
- MARKETS_BINANCEDEX_API: https://dex.binance.org/api
- REST_API_CHARTS_CACHE_CONTROL: 10m
- REST_API_MODE: release
- MARKETS_COINGECKO_API: https://api.coingecko.com/api
- MARKETS_FIXER_KEY: null
- REST_API_UPDATE_TIME_MEMORY_CACHE_TICKERS: 30s
- REST_API_TICKERS_RESPECTABLE_VOLUME: 0
- REST_API_TICKERS_CACHE_CONTROL: 1m
- REST_API_TICKERS_RESPECTABLE_MARKET_CAP: 0
- WORKER_BATCH_LIMIT: 3000
- MARKETS_PRIORITY_COIN_INFO: coinmarketcap, coingecko
