test_api:
  apis: [base, tickers, charts, info, swagger, rates]
  mode: release
  port: 8421
  tickers:
    cache_control: 1m
    respectable_market_cap: 0
    respectable_volume: 0
    respectable_update_time: 72h