definitions:
  api.Coin:
    properties:
      coin:
        type: integer
      token_id:
        type: string
      type:
        type: string
    type: object
  api.TickerRequest:
    properties:
      assets:
        items:
          $ref: '#/definitions/api.Coin'
        type: array
      currency:
        type: string
    type: object
  watchmarket.ChartCoinInfo:
    properties:
      circulating_supply:
        type: number
      info:
        $ref: '#/definitions/watchmarket.CoinInfo'
        type: object
      market_cap:
        type: number
      total_supply:
        type: number
      volume_24:
        type: number
    type: object
  watchmarket.ChartData:
    properties:
      error:
        type: string
      prices:
        items:
          $ref: '#/definitions/watchmarket.ChartPrice'
        type: array
    type: object
  watchmarket.ChartPrice:
    properties:
      date:
        type: integer
      price:
        type: number
    type: object
  watchmarket.CoinInfo:
    properties:
      data_source:
        type: string
      description:
        type: string
      explorers:
        items:
          $ref: '#/definitions/watchmarket.Link'
        type: array
      name:
        type: string
      short_description:
        type: string
      socials:
        items:
          $ref: '#/definitions/watchmarket.SocialLink'
        type: array
      source_code:
        type: string
      website:
        type: string
      white_paper:
        type: string
    type: object
  watchmarket.Link:
    properties:
      name:
        type: string
      url:
        type: string
    type: object
  watchmarket.SocialLink:
    properties:
      handle:
        type: string
      name:
        type: string
      url:
        type: string
    type: object
  watchmarket.Ticker:
    properties:
      coin:
        type: integer
      coin_name:
        type: string
      error:
        type: string
      last_update:
        type: string
      price:
        $ref: '#/definitions/watchmarket.TickerPrice'
        type: object
      token_id:
        type: string
      type:
        type: string
    type: object
  watchmarket.TickerPrice:
    properties:
      change_24h:
        type: number
      currency:
        type: string
      provider:
        type: string
      value:
        type: number
    type: object
  watchmarket.Tickers:
    items:
      $ref: '#/definitions/watchmarket.Ticker'
    type: array
info:
  contact: {}
  license: {}
paths:
  /v1/market/charts:
    get:
      consumes:
      - application/json
      description: Get the charts data from an market and coin/token
      operationId: get_charts_data
      parameters:
      - default: 60
        description: Coin ID
        in: query
        name: coin
        required: true
        type: integer
      - description: Token ID
        in: query
        name: token
        type: string
      - default: 1574483028
        description: Start timestamp
        in: query
        name: time_start
        type: integer
      - default: 64
        description: Max number of items in result prices array
        in: query
        name: max_items
        type: integer
      - default: USD
        description: The currency to show charts
        in: query
        name: currency
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/watchmarket.ChartData'
      summary: Get charts data for a specific coin
      tags:
      - Market
  /v1/market/info:
    get:
      consumes:
      - application/json
      description: Get the charts coin info data from an market and coin/contract
      operationId: get_charts_coin_info
      parameters:
      - default: 60
        description: Coin ID
        in: query
        name: coin
        required: true
        type: integer
      - description: Token ID
        in: query
        name: token
        type: string
      - default: 1574483028
        description: Start timestamp
        in: query
        name: time_start
        type: integer
      - default: USD
        description: The currency to show coin info in
        in: query
        name: currency
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/watchmarket.ChartCoinInfo'
      summary: Get charts coin info data for a specific coin
      tags:
      - Market
  /v1/market/ticker:
    post:
      consumes:
      - application/json
      description: Get the ticker values from many market and coin/token
      operationId: get_tickers
      parameters:
      - description: Ticker
        in: body
        name: tickers
        required: true
        schema:
          $ref: '#/definitions/api.TickerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/watchmarket.Tickers'
      summary: Get ticker values for a specific market
      tags:
      - Market
swagger: "2.0"
